version: "3.9"

services:
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: Backend
    env_file:
      - ./Backend/.env
    ports:
      - 3000:3000
    volumes:
      - ./Backend:/app
      - api_node_modules:/app/node_modules
    command: ["node", "index.js"]
    networks: [app]
  frontend:
    build:
      context: ./javisefront
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - NODE_ENV=development
    ports:
      - 4200:4200
    volumes:
      - ./javisefront:/app
      - web_node_modules:/app/node_modules
    command: ["ng", "serve", "--host", "0.0.0.0"]
    networks: [app]
networks:
  app:
volumes:
  api_node_modules:
  web_node_modules: